\context ChordNames
	\chords {
		\set majorSevenSymbol = \markup { "maj7" }
		\set chordChanges = ##t

		R2.

		% intro
		e2. | fis2.:m | gis2.:m | a2. |
		e2. | b2.:7 | e2. | e2. |

		% aleluya (mi)
		e2. | fis2.:m | a2. | b2. |
		e2. | fis2.:m | a4 b2 |
		%
		e2. | fis2.:m | a2. | b2. |
		e2. | fis2.:m | a4 b2 |

		% aleluya (fa#)
		fis2. | gis2.:m | b2. | cis2. |
		fis2. | gis2.:m | b4 cis2 |
		%
		fis2. | gis2.:m | b2. | cis2. |
		fis2. | gis2.:m | b4 cis2 |

		% aclamacion
		a2. | a2.:/gis | a2.:/fis | a2.:/e |
		d2. | d2. | e2. | e2. |
		a2. | a2.:/gis | a2.:/fis | a2.:/e |
		d2. | d2. | e2. | e2. |
		d2. | d2. | e2. | e2. |
		%R2.*20 |

		% aleluya (fa#)
		fis2. | gis2.:m | b2. | cis2. |
		fis2. | gis2.:m | b4 cis2 |
		%
		fis2. | gis2.:m | b2. | cis2. |
		fis2. | gis2.:m | b4 cis2 |
		%
		fis2. | gis2.:m | b2. | cis2. |
		fis2. | gis2.:m | b4 cis2 |

		% outro
		fis2. | gis2.:m | ais2.:m | b2. |
		fis2. | cis2.:7 | fis2. | fis2.
	}
